In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('lastECommerce.csv')

In [34]:
df['Comment_id']=df['comment_ids'].apply(lambda x:x.split('-')[-1])

In [44]:
top_sell_items_df = df.groupby('product_name').agg({'product_ratings(out of 5)':'sum'})

top_sell_items_df.reset_index(inplace=True)


    # Rank the product by most Qty sold
top_sell_items_df['Top_Sell_Rank'] = top_sell_items_df['product_ratings(out of 5)'].rank(method='min',ascending=False).astype(int)

In [46]:
top_sell_items_df.sort_values(by='Top_Sell_Rank',ascending=True)

,product_name,product_ratings(out of 5),Top_Sell_Rank
227,Jar Of Nothing,60.0,1
249,Magnet Mémoire – Moments in Magnets,50.0,2
146,Dedicate A Tree – Go Green in Love!,45.0,3
307,Photo Film Book,45.0,3
409,You Are My Soymate,45.0,3
...,...,...,...
175,Fine Dining by Moondrenched Poolside,5.0,175
174,Fascinating Poolside Dinner at Aloft,5.0,175
173,Family Miniature,5.0,175
170,Exotic Rooftop Candle Light Dinner,5.0,175
205,Holly Jolly Christmas Frame,5.0,175

In [57]:
df[df['product_name']=='You Are My Soymate']

,product_name,product_link,product_price(₹),product_ratings(out of 5),product_description,sub-category,Category,product_ids,comment_ids,Comment_id
28,You Are My Soymate,https://www.bookthesurprise.com/surprise/you-a...,499.0,5.0,This personalised anniversary frame lets your ...,anniversary-gifts,Surprise-Gifts,17368,comment-10324,10324
67,You Are My Soymate,https://www.bookthesurprise.com/surprise/you-a...,499.0,5.0,An HBD coffee mug of course!,birthday-gifts,Surprise-Gifts,17368,comment-10324,10324
393,You Are My Soymate,https://www.bookthesurprise.com/surprise/you-a...,499.0,5.0,Show your love and appreciation to your loved ...,gifts-for-boyfriend,Surprise-Gifts,17368,comment-10324,10324
462,You Are My Soymate,https://www.bookthesurprise.com/surprise/you-a...,499.0,5.0,Show your love and appreciation to your loved ...,gifts-for-friend,Surprise-Gifts,17368,comment-10324,10324
493,You Are My Soymate,https://www.bookthesurprise.com/surprise/you-a...,499.0,5.0,This innovative birthday gift comes with a spe...,gifts-for-girlfriend,Surprise-Gifts,17368,comment-10324,10324
529,You Are My Soymate,https://www.bookthesurprise.com/surprise/you-a...,499.0,5.0,You Are My Soymate,gifts-for-her,Surprise-Gifts,17368,comment-10324,10324
563,You Are My Soymate,https://www.bookthesurprise.com/surprise/you-a...,499.0,5.0,Show your love and appreciation to your loved ...,gifts-for-him,Surprise-Gifts,17368,comment-10324,10324
831,You Are My Soymate,https://www.bookthesurprise.com/surprise/you-a...,499.0,5.0,Photo Magnet With Some Clever Food Puns to Win...,personalized-gifts,Surprise-Gifts,17249,comment-10324,10324
967,You Are My Soymate,https://www.bookthesurprise.com/surprise/you-a...,499.0,5.0,"In addition to this, you can write customised ...",valentines-day,Surprise-Gifts,22886,comment-10324,10324